name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag-and-publish:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[bump-patch]') || contains(github.event.head_commit.message, '[bump-minor]') || contains(github.event.head_commit.message, '[bump-major]')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tags
        run: git fetch --tags origin

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Bump version
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"[bump-patch]"* ]]; then
            ./gradlew release -Prelease.incrementer=incrementPatch
          elif [[ "${{ github.event.head_commit.message }}" == *"[bump-minor]"* ]]; then
            ./gradlew release -Prelease.incrementer=incrementMinor
          elif [[ "${{ github.event.head_commit.message }}" == *"[bump-major]"* ]]; then
            ./gradlew release -Prelease.incrementer=incrementMajor
          fi

      - name: Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push --follow-tags

      - name: Project version
        run: ./gradlew properties | grep "version"

      - name: Build and publish fixturize-core
        run: ./gradlew publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}