name: Release Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          fetch-tags: 'true'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Extract bump type and commit message
        id: extract_bump
        run: ./run.sh extract-bump

      - name: Build and Test
        run: ./gradlew clean build

      - name: Get previous tag
        if: steps.extract_bump.outputs.BUMP_TYPE != ''
        id: get_previous_tag
        run: ./run.sh get-previous-tag

      - name: Calculate new version
        if: steps.extract_bump.outputs.BUMP_TYPE != ''
        id: calculate_version
        run: ./run.sh bump-version ${{ steps.get_previous_tag.outputs.PREVIOUS_TAG }} ${{ steps.extract_bump.outputs.BUMP_TYPE }}

      - name: Create Git Tag
        if: steps.extract_bump.outputs.BUMP_TYPE != ''
        run: ./run.sh create-new-tag ${{ steps.calculate_version.outputs.NEW_VERSION }}

      - name: Set release body
        if: steps.extract_bump.outputs.BUMP_TYPE != ''
        id: set_release_body
        run: ./run.sh create-release-body ${{ steps.get_previous_tag.outputs.PREVIOUS_TAG }} ${{ steps.calculate_version.outputs.NEW_VERSION }} ${{ steps.extract_bump.outputs.MESSAGE_BODY }} ${{ github.repository }}

      - name: Create GitHub Release
        if: steps.extract_bump.outputs.BUMP_TYPE != ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.calculate_version.outputs.NEW_VERSION }}
          release_name: ${{ steps.calculate_version.outputs.NEW_VERSION }}
          body: ${{ steps.set_release_body.outputs.RELEASE_BODY }}
          draft: false
          prerelease: false

      - name: Publish to Maven Central
        if: steps.extract_bump.outputs.BUMP_TYPE != ''
        run: ./gradlew publish -Pversion=${{ steps.extract_version.outputs.VERSION }}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}