name: Release Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Extract version and commit message
        id: extract_version
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if [[ $COMMIT_MESSAGE =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            VERSION=$(echo $COMMIT_MESSAGE | awk '{print $1}')
            MESSAGE_BODY=$(echo $COMMIT_MESSAGE | sed -e "s/$VERSION //")
            echo "::set-output name=VERSION::$VERSION"
            echo "::set-output name=MESSAGE_BODY::$MESSAGE_BODY"
          else
            echo "::set-output name=VERSION::"
            echo "::set-output name=MESSAGE_BODY::$COMMIT_MESSAGE"
          fi

      - name: Build and Test
        run: ./gradlew clean build

      - name: Create Git Tag
        if: steps.extract_version.outputs.VERSION != ''
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git tag ${{ steps.extract_version.outputs.VERSION }}
          git push origin ${{ steps.extract_version.outputs.VERSION }}

      - name: Create GitHub Release
        if: steps.extract_version.outputs.VERSION != ''
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.extract_version.outputs.VERSION }}
          release_name: ${{ steps.extract_version.outputs.VERSION }}
          body: ${{ steps.extract_version.outputs.MESSAGE_BODY }}
          draft: false
          prerelease: false

      - name: Publish to Maven Central
        if: steps.extract_version.outputs.VERSION != ''
        run: ./gradlew publish -Pversion=${{ steps.extract_version.outputs.VERSION }}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}