name: Release

on:
  push:
    branches:
      - main

jobs:
  version-bump:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[bump-patch]') || contains(github.event.head_commit.message, '[bump-minor]') || contains(github.event.head_commit.message, '[bump-major]')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Bump version
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"[bump-patch]"* ]]; then
            ./gradlew release -Prelease.incrementer=incrementPatch
          elif [[ "${{ github.event.head_commit.message }}" == *"[bump-minor]"* ]]; then
            ./gradlew release -Prelease.incrementer=incrementMinor
          elif [[ "${{ github.event.head_commit.message }}" == *"[bump-major]"* ]]; then
            ./gradlew release -Prelease.incrementer=incrementMajor
          fi

      - name: Push changes
        env:
          GH_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/floydkretschmar/fixturize.git
          git push --follow-tags

  publish:
    runs-on: ubuntu-latest
    needs: version-bump
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and publish
        run: ./gradlew :fixturize-core:publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}